const task1 = require("./task1.js")
const task2 = require("./task2.js")
const task3 = require("./task3.js")
const task4 = require("./task4.js")
const task5 = require("./task5.js")
const {task6m1, task6m2} = require("./task6.js")
const task7 = require("./task7.js")
const task8 = require("./task8.js")

task8(" anya lutshaya")