// /*console.log("1 * "+a+" = "+(a*1))
// console.log("2 * "+a+" = "+(a*2))
// console.log("3 * "+a+" = "+(a*3))
// console.log("4 * "+a+" = "+(a*4))
// console.log("5 * "+a+" = "+(a*5))
// console.log("6 * "+a+" = "+(a*6))
// console.log("7 * "+a+" = "+(a*7))
// console.log("8 * "+a+" = "+(a*8))
// console.log("9 * "+a+" = "+(a*9))
// console.log("10 * "+a+" = "+(a*10))*/
// let a = Math.floor(Math.random()*100)
// let b = Math.floor(Math.random()*100)
// let c = Math.floor(Math.random()*100)
// console.log ("Сторона квадрата "+a+"см")
// console.log("Площа квадратa з стороною "+a+"cм буде " +(a*a)+"см^2")
// console.log ("Перша сторона прямокутника "+b+"см")
// console.log ("Друга сторона прямокутника "+c+"см")
// console.log("Периметр прямокутника зі сторононами "+b+"см і "+c+"см"+" буде " +(2*(b+c))+"см")
let name = prompt("Який в тебе рік народження"," 1999")
alert(`Тобі, ${2023-name},років`)


